# Generated by Django 3.2.5 on 2021-07-09 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterField(
            model_name='departments',
            name='description',
            field=models.TextField(verbose_name=' Описание отдела'),
        ),
        migrations.AlterField(
            model_name='departments',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Название отдела'),
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Название должности')),
                ('description', models.TextField(verbose_name=' Описание должности')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='main.departments', verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
    ]
