# Generated by Django 3.2.5 on 2021-07-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210709_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Имя')),
                ('position_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='main.positions', verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
