# Generated by Django 3.2.5 on 2021-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='middle_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workers',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
    ]
