# Generated by Django 3.2.5 on 2021-07-09 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_personinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personinfo',
            options={'verbose_name': 'Личная информация', 'verbose_name_plural': 'Личная информация'},
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Работодатель')),
                ('post', models.CharField(max_length=30, verbose_name='Должность')),
                ('duration', models.CharField(max_length=30, verbose_name='Длительность')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp', to='main.workers', verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Опыт работы',
                'verbose_name_plural': 'Опыт работы',
            },
        ),
    ]
